apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpaperdelivery
  labels:
    app: tpaperdelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tpaperdelivery
  template:
    metadata:
      labels:
        app: tpaperdelivery
        service: tpaperdelivery
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tpaperdelivery"
        dapr.io/app-port: "80"
        dapr.io/log-level: debug
    spec:
      containers:
        - name: tpaperdelivery
          image: netfwdaysregistry.azurecr.io/tpaperdelivery:v14
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: SqlDeliveryString
              value: Server=tcp:fwdays.database.windows.net,1433;Initial Catalog=deliveries;Persist Security Info=False;User ID=FancyUser3;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
            - name: SqlPaperPassword
              value: secret
---
apiVersion: v1
kind: Service
metadata:
  name: tpaperdelivery
  labels:
    app: tpaperdelivery
    service: tpaperdelivery
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: tpaperdelivery